#include "dispatcher.hpp"
#include "main_thread.hpp"

namespace arc {

CommandDispatcher::CommandDispatcher(ipc::Server& server, WindowRegistry& registry)
    : server_(server), registry_(registry) {}

void CommandDispatcher::emit(nlohmann::json evt) {
    server_.send(std::move(evt));
}

void CommandDispatcher::dispatch(const ipc::Message& msg) {
    if (msg.type != ipc::MessageType::JSON) return;

    const auto j = msg.json();
    if (!j.contains("type") || !j["type"].is_string()) return;

    const std::string t = j["type"];

    if      (t == "host.configure")            on_host_configure(j);
    else if (t == "host.ping")                 on_host_ping();
    else if (t == "host.shutdown")             on_host_shutdown();

    else if (t == "window.create")             on_window_create(j);
    else if (t == "window.destroy")            on_window_destroy(j);
    else if (t == "window.set_title")          on_window_set_title(j);
    else if (t == "window.set_size")           on_window_set_size(j);
    else if (t == "window.set_position")       on_window_set_position(j);
    else if (t == "window.center")             on_window_center(j);
    else if (t == "window.show")               on_window_show(j);
    else if (t == "window.hide")               on_window_hide(j);
    else if (t == "window.focus")              on_window_focus(j);
    else if (t == "window.minimize")           on_window_minimize(j);
    else if (t == "window.maximize")           on_window_maximize(j);
    else if (t == "window.restore")            on_window_restore(j);
    else if (t == "window.set_fullscreen")     on_window_set_fullscreen(j);
    else if (t == "window.set_min_size")       on_window_set_min_size(j);
    else if (t == "window.set_max_size")       on_window_set_max_size(j);
    else if (t == "window.set_always_on_top")  on_window_set_always_on_top(j);
    else if (t == "window.set_effect")         on_window_set_effect(j);
    else if (t == "window.clear_effect")       on_window_clear_effect(j);

    else if (t == "webview.create")            on_webview_create(j);
    else if (t == "webview.destroy")           on_webview_destroy(j);
    else if (t == "webview.load_url")          on_webview_load_url(j);
    else if (t == "webview.load_html")         on_webview_load_html(j);
    else if (t == "webview.load_file")         on_webview_load_file(j);
    else if (t == "webview.reload")            on_webview_reload(j);
    else if (t == "webview.go_back")           on_webview_go_back(j);
    else if (t == "webview.go_forward")        on_webview_go_forward(j);
    else if (t == "webview.eval")              on_webview_eval(j);
    else if (t == "webview.set_zoom")          on_webview_set_zoom(j);
    else if (t == "webview.send_ipc")          on_webview_send_ipc(j);
    else if (t == "webview.set_position")      on_webview_set_position(j);
    else if (t == "webview.set_size")          on_webview_set_size(j);
    else if (t == "webview.show")              on_webview_show(j);
    else if (t == "webview.hide")              on_webview_hide(j);
    else if (t == "webview.set_zorder")        on_webview_set_zorder(j);
}

// ── Host ──────────────────────────────────────────────────────────────────────

void CommandDispatcher::on_host_configure(const nlohmann::json& j) {
    if (j.contains("app_name") && j["app_name"].is_string())
        app_name_ = j["app_name"];
    emit({ {"type", "host.configured"} });
}

void CommandDispatcher::on_host_ping() {
    emit({ {"type", "host.pong"} });
}

void CommandDispatcher::on_host_shutdown() {
    arc::quit_app();
}

// ── Window ────────────────────────────────────────────────────────────────────

void CommandDispatcher::on_window_create(const nlohmann::json& j) {
    const std::string id    = j.value("id", "");
    const std::string style = j.value("style", "default");

    ui::WindowStyle wstyle = ui::WindowStyle::Default;
    if      (style == "border_only") wstyle = ui::WindowStyle::BorderOnly;
    else if (style == "borderless")  wstyle = ui::WindowStyle::Borderless;

    ui::WindowConfig cfg;
    cfg.title     = j.value("title", "");
    cfg.size      = { j.value("width", 800), j.value("height", 600) };
    cfg.resizable = j.value("resizable", true);
    cfg.style     = wstyle;

    auto* mw = registry_.create_window(id, std::move(cfg));
    if (!mw) return;

    wire_window_events(id, *mw->win);

    // Emit initial geometry so Go has accurate values before any resize/move
    // events are generated by the user.
    const auto sz  = mw->win->get_size();
    const auto pos = mw->win->get_position();
    // Report content-area size (same value the fixed windowDidResize sends).
    emit({ {"type", "window.resized"}, {"id", id},
           {"width", sz.width}, {"height", sz.height} });
    emit({ {"type", "window.moved"}, {"id", id},
           {"x", pos.x}, {"y", pos.y} });
}

void CommandDispatcher::wire_window_events(const std::string& id, ui::Window& win) {
    win.on_resize([this, id](ui::Size s) {
        emit({ {"type", "window.resized"}, {"id", id},
               {"width", s.width}, {"height", s.height} });
    });

    win.on_move([this, id](ui::Point p) {
        emit({ {"type", "window.moved"}, {"id", id}, {"x", p.x}, {"y", p.y} });
    });

    win.on_focus([this, id]() {
        emit({ {"type", "window.focused"}, {"id", id} });
    });

    win.on_blur([this, id]() {
        emit({ {"type", "window.blurred"}, {"id", id} });
    });

    win.on_state_change([this, id](ui::WindowState state) {
        std::string s;
        switch (state) {
            case ui::WindowState::Normal:     s = "normal";     break;
            case ui::WindowState::Minimized:  s = "minimized";  break;
            case ui::WindowState::Maximized:  s = "maximized";  break;
            case ui::WindowState::Fullscreen: s = "fullscreen"; break;
        }
        emit({ {"type", "window.state_changed"}, {"id", id}, {"state", s} });
    });

    win.on_close([this, id]() -> bool {
        emit({ {"type", "window.closed"}, {"id", id} });
        return true;
    });
}

void CommandDispatcher::on_window_destroy(const nlohmann::json& j) {
    registry_.destroy_window(j.value("id", ""));
}

void CommandDispatcher::on_window_set_title(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->set_title(j.value("title", ""));
}

void CommandDispatcher::on_window_set_size(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->set_size({ j.value("width", 800), j.value("height", 600) });
}

void CommandDispatcher::on_window_set_position(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->set_position({ j.value("x", 0), j.value("y", 0) });
}

void CommandDispatcher::on_window_center(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->center();
}

void CommandDispatcher::on_window_show(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->show();
}

void CommandDispatcher::on_window_hide(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->hide();
}

void CommandDispatcher::on_window_focus(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->focus();
}

void CommandDispatcher::on_window_minimize(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->minimize();
}

void CommandDispatcher::on_window_maximize(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->maximize();
}

void CommandDispatcher::on_window_restore(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->restore();
}

void CommandDispatcher::on_window_set_fullscreen(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->set_fullscreen(j.value("fullscreen", false));
}

void CommandDispatcher::on_window_set_min_size(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->set_min_size({ j.value("width", 0), j.value("height", 0) });
}

void CommandDispatcher::on_window_set_max_size(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->set_max_size({ j.value("width", 0), j.value("height", 0) });
}

void CommandDispatcher::on_window_set_always_on_top(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->set_always_on_top(j.value("value", false));
}

// ── Effect helpers ────────────────────────────────────────────────────────────

std::optional<ui::BackdropEffect>
CommandDispatcher::parse_effect(const std::string& name) {
    if (name == "vibrancy")  return ui::BackdropEffect::Vibrancy;
    if (name == "acrylic")   return ui::BackdropEffect::Acrylic;
    if (name == "mica")      return ui::BackdropEffect::Mica;
    if (name == "mica_alt")  return ui::BackdropEffect::MicaAlt;
    return std::nullopt;
}

void CommandDispatcher::on_window_set_effect(const nlohmann::json& j) {
    auto* mw = registry_.get_window(j.value("id", ""));
    if (!mw) return;
    const std::string name = j.value("effect", "");
    if (auto effect = parse_effect(name))
        mw->win->set_effect(*effect);
}

void CommandDispatcher::on_window_clear_effect(const nlohmann::json& j) {
    if (auto* mw = registry_.get_window(j.value("id", "")))
        mw->win->clear_effect();
}

// ── WebView ───────────────────────────────────────────────────────────────────

void CommandDispatcher::on_webview_create(const nlohmann::json& j) {
    const std::string id     = j.value("id", "");
    const std::string win_id = j.value("window_id", "");
    const std::string mode   = j.value("mode", "window");

    webview::WebViewConfig cfg;
    cfg.devtools = j.value("devtools", false);

    webview::WebView* wv = nullptr;

    if (mode == "window") {
        wv = registry_.create_window_webview(id, win_id, std::move(cfg));
    } else if (mode == "view") {
        ui::ViewConfig vcfg;
        vcfg.position = { j.value("x", 0),      j.value("y", 0)       };
        vcfg.size     = { j.value("width", 400), j.value("height", 300) };
        wv = registry_.create_view_webview(id, win_id, std::move(vcfg), std::move(cfg));

        // Apply initial z-order; reorder_views sorts and restacks all overlays.
        if (wv)
            registry_.set_view_zorder(id, j.value("z", 0));
    }

    if (!wv) return;
    wire_webview_events(id, *wv);
}

void CommandDispatcher::wire_webview_events(const std::string& id, webview::WebView& wv) {
    wv.on_ready([this, id]() {
        emit({ {"type", "webview.ready"}, {"id", id} });
    });

    wv.on_load_start([this, id](webview::LoadEvent& ev) {
        emit({ {"type", "webview.load_start"}, {"id", id}, {"url", ev.url} });
    });

    wv.on_load_finish([this, id](webview::LoadEvent& ev) {
        emit({ {"type", "webview.load_finish"}, {"id", id}, {"url", ev.url} });
    });

    wv.on_load_failed([this, id](webview::LoadFailedEvent& ev) {
        emit({ {"type", "webview.load_failed"}, {"id", id},
               {"url", ev.url}, {"error", ev.error_description} });
    });

    wv.on_navigate([this, id](webview::NavigationEvent& ev) {
        emit({ {"type", "webview.navigate"}, {"id", id}, {"url", ev.url} });
    });

    wv.on_title_change([this, id](std::string title) {
        emit({ {"type", "webview.title"}, {"id", id}, {"title", title} });
    });

    wv.on_console_message([this, id](webview::ConsoleMessage& msg) {
        std::string level;
        switch (msg.level) {
            case webview::ConsoleLevel::Log:   level = "log";   break;
            case webview::ConsoleLevel::Info:  level = "info";  break;
            case webview::ConsoleLevel::Warn:  level = "warn";  break;
            case webview::ConsoleLevel::Error: level = "error"; break;
            default:                           level = "log";   break;
        }
        emit({ {"type", "webview.console"}, {"id", id},
               {"level", level}, {"text", msg.text} });
    });

    wv.ipc.on("*", [this, id](webview::Message& msg) {
        emit({ {"type",    "webview.ipc"},
               {"id",      id},
               {"channel", msg.channel},
               {"body",    msg.body} });
    });
}

void CommandDispatcher::on_webview_destroy(const nlohmann::json& j) {
    registry_.destroy_webview(j.value("id", ""));
}

void CommandDispatcher::on_webview_load_url(const nlohmann::json& j) {
    if (auto* wv = registry_.get_webview(j.value("id", "")))
        wv->load_url(j.value("url", ""));
}

void CommandDispatcher::on_webview_load_html(const nlohmann::json& j) {
    if (auto* wv = registry_.get_webview(j.value("id", "")))
        wv->load_html(j.value("html", ""));
}

void CommandDispatcher::on_webview_load_file(const nlohmann::json& j) {
    if (auto* wv = registry_.get_webview(j.value("id", "")))
        wv->load_file(j.value("path", ""));
}

void CommandDispatcher::on_webview_reload(const nlohmann::json& j) {
    if (auto* wv = registry_.get_webview(j.value("id", "")))
        wv->reload();
}

void CommandDispatcher::on_webview_go_back(const nlohmann::json& j) {
    if (auto* wv = registry_.get_webview(j.value("id", "")))
        wv->go_back();
}

void CommandDispatcher::on_webview_go_forward(const nlohmann::json& j) {
    if (auto* wv = registry_.get_webview(j.value("id", "")))
        wv->go_forward();
}

void CommandDispatcher::on_webview_eval(const nlohmann::json& j) {
    if (auto* wv = registry_.get_webview(j.value("id", "")))
        wv->eval(j.value("js", ""), [](webview::EvalResult) {});
}

void CommandDispatcher::on_webview_set_zoom(const nlohmann::json& j) {
    if (auto* wv = registry_.get_webview(j.value("id", "")))
        wv->set_zoom(j.value("zoom", 1.0));
}

void CommandDispatcher::on_webview_send_ipc(const nlohmann::json& j) {
    auto* wv = registry_.get_webview(j.value("id", ""));
    if (!wv) return;
    const std::string    channel = j.value("channel", "");
    const nlohmann::json body    = j.contains("body") ? j["body"]
                                                       : nlohmann::json::object();
    wv->ipc.send(channel, body);
}

void CommandDispatcher::on_webview_set_position(const nlohmann::json& j) {
    if (auto* mv = registry_.get_view(j.value("id", "")))
        mv->view->set_position({ j.value("x", 0), j.value("y", 0) });
}

void CommandDispatcher::on_webview_set_size(const nlohmann::json& j) {
    if (auto* mv = registry_.get_view(j.value("id", "")))
        mv->view->set_size({ j.value("width", 0), j.value("height", 0) });
}

void CommandDispatcher::on_webview_show(const nlohmann::json& j) {
    if (auto* mv = registry_.get_view(j.value("id", "")))
        mv->view->show();
}

void CommandDispatcher::on_webview_hide(const nlohmann::json& j) {
    if (auto* mv = registry_.get_view(j.value("id", "")))
        mv->view->hide();
}

void CommandDispatcher::on_webview_set_zorder(const nlohmann::json& j) {
    // set_view_zorder updates the ManagedView z_order field and immediately
    // re-sorts + restacks all overlay views on the owning window.
    registry_.set_view_zorder(j.value("id", ""), j.value("z", 0));
}

} // namespace arc